extends Node2D

var mum_num = 0
var mum_list = ["Mumble1", "Mumble2", "Mumble3", "Mumble4", "Mumble5", "Mumble6"]

var everything = ["…SIMPLICITY AT THE INCEPTION. TERRA, IGNIS, AQVA, AER. OF THESE BASE ELEMENTS ARE ALL THINGS…",
	".. I HAD NOTHING BVT DIRT AND STONE, BVT FROM DIRT AND STONE CAN FINER THINGS BE TRANSMVTED….",
	"…WATCHING THE CATERPILLAR BECOME THE BVTTERFLY AND MOTH. CHRYSOPOEIA WAS MY AMBITION. LEAD TO GOLD. BVT LEAD I HAD NOT. NAVGHT BVT DIRT AND STONE…",
	"… IGNIS AND TERRA. AQVA AND AER. THE COALESCENCES KNEW NO BOVNDARY…",
	"….. VPON MIXING AMALGAM AFTER ANOTHER, I AT LAST HAD NO LONGER A HARD STONE, BVT A SOFT, DARK METAL….",
	"… WORTH IT HAD CLOSE TO NONE. BVT TO CREATE IT FROM NAVGHT BVT THE DVST WE TROD ON…",
	"WITHIN YEARS I HAD ENOVGH COIN TO STVDY… YEARS VNDER THE DIRECTION OF THE MASTERS TO NEW HEIGHTS ELEVATED ME…",
	"…SALT AND SILVER, GOLD AND IRON, BISMVTH AND POTASSIVM… DEEPER I DELVED REALIZING THAT THE BOVNDARIES I ONCE SAW WERE BVT THE SVRFACE VPON THE DEPTHS…..",
	"…REALIZING THE ALCHEMY TAKING PLACE WITHIN MY BODY EVERY MOMENT. IF I GAVE TO MY BODY THAT WHICH MADE MY FLESH AND BLOOD, THEN PERHAPS…",
	"…DESTITVTE NEVERMORE, FOR I HAD DONE IT. BEFORE ME LAY MY BVTTERFLY AT LAST. THE CHRYSOPOEIA WAS FINISHED AND FOR ONLY A CVT PALM…",
	" …NEW FOVND WEALTH GAVE ME FREEDOMS TO EXPLORE THAT WHICH WOVLD HAVE NEVER BEEN POSSIBLE… DEEPER PVRSVITS WERE NECESSARY… THE ELIXIR OF LIFE, THE PHILOSOPHER’S STONE… ",
	"…AS FAR AS THE CREATION OF LIFE, DEEPER VNDERSTANDINGS WERE NEEDED. DID THE SOVL HAVE A FORM? …. SALT, MERCVRY, SVLFVR?...",
	"…TO CREATE REQVIRES DESTRVCTION. AS FIRE CONSVMES THE TIMBER AND THE TIMBER CONSVMES THE WATER… LIFE CANNOT EXIST WITHOVT DEATH, AS LIGHT CANNOT EXIST WITHOVT DARKNESS…",
	"…AS ABOVE, SO BELOW…",
	"…NO CLOSER TO THE PHILOSOPHER’S STONE NOR THE ELIXIR OF LIFE… LIKE THE MOON AFTER THE HARVEST MY LIFE TOO BEGINS TO WANE. A PROTEGE, A PVPIL…",
	"…NAVGHT BETTER THAN HE WHO VNDERSTANDS MY ART AS WELL AS I… BVT CAN A SOVL BE FRACTVRED?......",
	"…IT IS DONE, BVT SO TOO AM I… I CAN ONLY HOPE THE ONE WHO  SVPERCEEDS ME SVCCEEDS WHERE I HAVE FAILED…."]

func _on_timer_timeout():
	if $CanvasLayer/RichTextLabel.visible_ratio != 1:
		$CanvasLayer/RichTextLabel.visible_characters += 1
		$CanvasLayer/Timer.start()
	else:
		$WaitTimer.start()
		get_node(mum_list[mum_num]).stop()


func _on_lore_loretime(num):
	$CanvasLayer/RichTextLabel.text = everything[num]
	$CanvasLayer/RichTextLabel.visible_characters = 0
	$CanvasLayer.visible = true
	$CanvasLayer/Timer.start()
	mum_num = randi_range(0,5)
	get_node(mum_list[mum_num]).play()
	


func _on_wait_timer_timeout():
	$CanvasLayer/RichTextLabel.visible_characters = 0
	$CanvasLayer.visible = false



func _on_mumble_finished():
	mum_num = randi_range(0,5)
	get_node(mum_list[mum_num]).play()
